services:
    chronos_api:
        # build: 
        #     context: .
        #     dockerfile: dockerfile.dev
        image: devamade/chronos_api:8fe392e26e816d645fe155f15c53f2759044b0b2
        container_name: chronos_api
        ports:
            - "3000:3000"
        networks:
            - chronos_network
        # env_file:
        #     - .env.docker
        depends_on:
            - chronos_database
    chronos_database:
        image: postgres:latest
        container_name: chronos_database
        ports:
            - "5432:5432"
        networks:
            - chronos_network
        volumes:
            - chronos_data:/var/lib/postgresql/data
            - ./sql/database_creation.sql:/docker-entrypoint-initdb.d/database_creation.sql
        env_file:
            - .env.db

networks:
    chronos_network:
        driver: bridge

volumes:
    chronos_data:
        driver: local