FROM node:latest

WORKDIR /chronos_backend_app/

COPY dist/ /chronos_backend_app/dist/
# COPY src/ /chronos_backend_app/src/
# COPY package*.json /chronos_backend_app/
# COPY tsconfig*.json /chronos_backend_app/

# RUN npm install --production
# RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start:prod"]