services:
    chronos_api:
        build: ./
        container_name: chronos_api
        ports:
            - "3000:3000"
        networks:
            - chronos_network
        env_file:
            - .env.prod
        depends_on:
            - chronos_database
    chronos_database:
        image: postgres:latest
        container_name: chronos_database
        ports:
            - "5432:5432"
        networks:
            - chronos_network
        volumes:
            - chronos_data:/var/lib/postgresql/data
            - ./db:/docker-entrypoint-initdb.d
        env_file:
            - .env.db

networks:
    chronos_network:
        driver: bridge

volumes:
    chronos_data:
        driver: local