name: Chronos API CI

on: 
    push:
        branches: 
            - main
            - devel
            - Docker_CI/CD
    pull_request:
        branches: 
            - main
            - devel

jobs:

    chronos_api_CI:

        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./chronos_backend_app
        
        env:
            DATABASE_DIALECT: postgres
            DATABASE_HOST: localhost
            DATABASE_PORT: 5432
            DATABASE_USERNAME: postgres
            DATABASE_PASSWORD: postgres
            DATABASE_TEST_NAME: chronos_database_test
            JWT_KEY_ADMIN: secret_key_admin
            JWT_KEY_PLAYER: secret_key_player
        
        services:
            postgres:
                image: postgres:latest
                options: >-
                    --health-cmd="pg_isready -U postgres"
                    --health-timeout=5s
                    --health-start-period=10s
                    --health-interval=5s
                ports:
                    - 5432:5432
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres

        steps:
            - name: Checkout source code
              uses: actions/checkout@v4
            
            # - name: Change directory
            #   run: cd chronos_backend_app

            # - name: Set up Node
            #   uses: actions/setup-node@v4
            #   with:
            #     node-version: 20.x
            #     cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Set up database for tests
              run: PGPASSWORD=postgres psql -h localhost -U postgres -a -f "./sql/database_test_creation.sql"
              run: PGPASSWORD=postgres psql -h localhost -U postgres -a -f "./sql/seed.sql"

            # - name: Set up database 2/2
            #   run: PGPASSWORD=postgres psql -h localhost -U postgres -a -f "./sql/seed.sql"

            - name: Run test e2e
              run: npm run test:e2e

            - name: Build project
              run: npm run build